name: Go Format and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  go-format-build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23  # 必要に応じてバージョンを指定

    - name: Install dependencies
      run: go mod download

    - name: Run gofmt
      run: gofmt -l -s -w .

    - name: Build the project
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...
